// src/api/mockData.js
import Slide1 from "../assets/Slides/Slide-1.jpg";
import Slide2 from "../assets/Slides/Slide-2.jpg";

export const mockData = {
  // Page metadata
  meta: {
    title: "SazzBazar - Premium Products for Everyone",
    description:
      "Fresh groceries, honey, ghee, daily essentials delivered fast at your doorstep",
    keywords: "honey, ghee, dates, oils, chocolates, beauty care, baby care",
  },

  // Slideshow configuration
  slideshow: {
    enabled: true,
    slides: [
      { id: 1, image: Slide1, alt: "Slider 1" },
      { id: 2, image: Slide2, alt: "Slider 2" },
    ],
  },

  // Categories configuration
  categories: {
    enabled: true,
    title: "Shop by Category",
    items: [
      { name: "Balm/Ointment", icon: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/bandcamp.svg", slug: "balm-ointment" },
      { name: "Foods", icon: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/food.svg", slug: "foods" },
      { name: "Dates", icon: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/datadog.svg", slug: "dates" },
      { name: "Gear & Gadgets", icon: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/gear.svg", slug: "gear-gadgets" },
      { name: "Chocolates", icon: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/heart.svg", slug: "chocolates" },
      { name: "Hair Care", icon: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/spa.svg", slug: "hair-care" },
      { name: "Oil", icon: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/oil.svg", slug: "oil" },
      { name: "Milk", icon: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/dropbox.svg", slug: "milk" },
      { name: "Tea & Coffee", icon: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/coffee.svg", slug: "tea-coffee" },
      { name: "Perfume/Attar", icon: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/seedling.svg", slug: "perfume-attar" },
      { name: "Nuts", icon: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/leaf.svg", slug: "nuts" },
      { name: "Beauty Care", icon: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/spa.svg", slug: "beauty-care" },
      { name: "Baby Care", icon: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/baby.svg", slug: "baby-care" },
      { name: "Honey", icon: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/honey.svg", slug: "honey" },
      { name: "Winter Care", icon: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/snowflake.svg", slug: "winter-care" },
      { name: "Skin Care", icon: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/spa.svg", slug: "skin-care" },
      { name: "Supplements", icon: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/health.svg", slug: "supplements" },
      { name: "Spices", icon: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/leaf.svg", slug: "spices" },
      { name: "Beverages", icon: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/drink.svg", slug: "beverages" },
      { name: "Snacks", icon: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/food.svg", slug: "snacks" },
      { name: "Oral Care", icon: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/health.svg", slug: "oral-care" },
      { name: "Fragrance", icon: "https://cdn.jsdelivr.net/npm/simple-icons@v9/icons/seedling.svg", slug: "fragrance" },
    ],
  },

  // Product sections
  productSections: [
    {
      id: "featured",
      enabled: true,
      title: "Featured Products",
      subtitle: "Handpicked favorites just for you",
      badge: "HOT",
      columns: 4,
      cardStyle: "default",
      bgColor: "bg-white",
      products: [
        {
          id: 1,
          name: "Organic Honey - Pure & Natural",
          category: "Honey",
          price: 1559,
          originalPrice: 1919,
          discount: 15,
          rating: 4.8,
          reviews: 124,
          slug: "organic-honey",
          image: "https://placehold.co/300x300/FFB300/FFFFFF?text=Honey",
          badge: "HOT",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/FFB300/FFFFFF?text=Honey+1", "https://placehold.co/600x600/F9A825/FFFFFF?text=Honey+2"],
          description: `<h3>Pure & Natural Organic Honey</h3><p>Our organic honey is sourced from sustainable farms and is 100% pure, raw, and unfiltered.</p>`,
        },
        {
          id: 2,
          name: "Premium Ghee - Clarified Butter",
          category: "Milk",
          price: 1079,
          originalPrice: null,
          rating: 4.9,
          reviews: 89,
          slug: "premium-ghee",
          image: "https://placehold.co/300x300/2E7D32/FFFFFF?text=Ghee",
          badge: "BEST",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/2E7D32/FFFFFF?text=Ghee+1", "https://placehold.co/600x600/1B5E20/FFFFFF?text=Ghee+2"],
          description: `<h3>Premium Quality Ghee</h3><p>Made from 100% pure cow's milk butter using traditional methods.</p>`,
        },
        {
          id: 3,
          name: "Basmati Rice - Aged 1 Year",
          category: "Foods",
          price: 1919,
          originalPrice: 2399,
          discount: 20,
          rating: 4.7,
          reviews: 56,
          slug: "basmati-rice",
          image: "https://placehold.co/300x300/FFD700/FFFFFF?text=Rice",
          badge: "SALE",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/FFD700/FFFFFF?text=Rice+1", "https://placehold.co/600x600/F9A825/FFFFFF?text=Rice+2"],
          description: `<h3>Premium Aged Basmati Rice</h3><p>Aged for 1 year to perfection, our basmati rice offers long, fluffy grains.</p>`,
        },
        {
          id: 4,
          name: "Extra Virgin Olive Oil",
          category: "Oil",
          price: 2759,
          originalPrice: null,
          rating: 4.6,
          reviews: 78,
          slug: "olive-oil",
          image: "https://placehold.co/300x300/4CAF50/FFFFFF?text=Olive",
          badge: "NEW",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/4CAF50/FFFFFF?text=Olive+1", "https://placehold.co/600x600/388E3C/FFFFFF?text=Olive+2"],
          description: `<h3>Premium Extra Virgin Olive Oil</h3><p>Cold-pressed from the finest olives, rich in healthy monounsaturated fats.</p>`,
        },
        {
          id: 5,
          name: "Organic Turmeric Powder",
          category: "Spices",
          price: 599,
          originalPrice: 799,
          discount: 25,
          rating: 4.8,
          reviews: 45,
          slug: "organic-turmeric",
          image: "https://placehold.co/300x300/F9A825/FFFFFF?text=Turmeric",
          badge: "BEST",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/F9A825/FFFFFF?text=Turmeric+1", "https://placehold.co/600x600/F57F17/FFFFFF?text=Turmeric+2"],
          description: `<h3>Organic Turmeric Powder</h3><p>Pure organic turmeric powder with high curcumin content.</p>`,
        },
        {
          id: 6,
          name: "Ceylon Cinnamon Sticks",
          category: "Spices",
          price: 899,
          originalPrice: null,
          rating: 4.9,
          reviews: 34,
          slug: "ceylon-cinnamon",
          image: "https://placehold.co/300x300/8D6E63/FFFFFF?text=Cinnamon",
          badge: "NEW",
          brand: "CeylonSpice",
          inStock: true,
          images: ["https://placehold.co/600x600/8D6E63/FFFFFF?text=Cinnamon+1", "https://placehold.co/600x600/6D4C41/FFFFFF?text=Cinnamon+2"],
          description: `<h3>Pure Ceylon Cinnamon Sticks</h3><p>Premium quality Ceylon cinnamon sticks with a sweet, delicate flavor.</p>`,
        },
      ],
    },
    {
      id: "top-selling",
      enabled: true,
      title: "Top Selling",
      subtitle: "Most loved by our customers",
      badge: "TRENDING",
      columns: 4,
      cardStyle: "featured",
      bgColor: "bg-amber-50/30",
      products: [
        {
          id: 7,
          name: "Medjool Dates - Premium Quality",
          category: "Dates",
          price: 2279,
          originalPrice: 2999,
          discount: 25,
          rating: 4.9,
          reviews: 234,
          slug: "medjool-dates",
          image: "https://placehold.co/300x300/8D6E63/FFFFFF?text=Dates",
          badge: "HOT",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/8D6E63/FFFFFF?text=Dates+1", "https://placehold.co/600x600/6D4C41/FFFFFF?text=Dates+2"],
          description: `<h3>Premium Medjool Dates</h3><p>Known as the "King of Dates," our Medjool dates are large, sweet, and delicious.</p>`,
        },
        {
          id: 8,
          name: "Almonds - California Grown",
          category: "Nuts",
          price: 1799,
          originalPrice: null,
          rating: 4.8,
          reviews: 167,
          slug: "almonds",
          image: "https://placehold.co/300x300/D7CCC8/000000?text=Almonds",
          badge: "BEST",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/D7CCC8/000000?text=Almonds+1", "https://placehold.co/600x600/BCAAA4/000000?text=Almonds+2"],
          description: `<h3>Premium California Almonds</h3><p>Carefully selected for their size, crunch, and nutritional value.</p>`,
        },
        {
          id: 9,
          name: "Dark Chocolate 70% Cocoa",
          category: "Chocolates",
          price: 839,
          originalPrice: 1079,
          discount: 22,
          rating: 4.7,
          reviews: 92,
          slug: "dark-chocolate",
          image: "https://placehold.co/300x300/4E342E/FFFFFF?text=Chocolate",
          badge: "SALE",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/4E342E/FFFFFF?text=Chocolate+1", "https://placehold.co/600x600/3E2723/FFFFFF?text=Chocolate+2"],
          description: `<h3>Premium Dark Chocolate 70% Cocoa</h3><p>Rich and smooth dark chocolate with 70% cocoa content.</p>`,
        },
        {
          id: 10,
          name: "Coconut Oil - Cold Pressed",
          category: "Oil",
          price: 1199,
          originalPrice: null,
          rating: 4.5,
          reviews: 145,
          slug: "coconut-oil",
          image: "https://placehold.co/300x300/F5F5F5/000000?text=Coconut",
          badge: "TRENDING",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/F5F5F5/000000?text=Coconut+1", "https://placehold.co/600x600/E0E0E0/000000?text=Coconut+2"],
          description: `<h3>Premium Cold-Pressed Coconut Oil</h3><p>Pure, unrefined coconut oil rich in medium-chain triglycerides.</p>`,
        },
        {
          id: 11,
          name: "Walnuts - Premium Quality",
          category: "Nuts",
          price: 1439,
          originalPrice: 1799,
          discount: 20,
          rating: 4.7,
          reviews: 89,
          slug: "walnuts",
          image: "https://placehold.co/300x300/A1887F/000000?text=Walnuts",
          badge: "POPULAR",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/A1887F/000000?text=Walnuts+1", "https://placehold.co/600x600/8D6E63/000000?text=Walnuts+2"],
          description: `<h3>Premium Walnuts</h3><p>High-quality walnuts rich in omega-3 fatty acids and antioxidants.</p>`,
        },
        {
          id: 12,
          name: "Pistachios - Roasted & Salted",
          category: "Nuts",
          price: 2159,
          originalPrice: null,
          rating: 4.9,
          reviews: 56,
          slug: "pistachios",
          image: "https://placehold.co/300x300/8BC34A/000000?text=Pistachios",
          badge: "NEW",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/8BC34A/000000?text=Pistachios+1", "https://placehold.co/600x600/689F38/000000?text=Pistachios+2"],
          description: `<h3>Roasted & Salted Pistachios</h3><p>Premium pistachios roasted to perfection and lightly salted.</p>`,
        },
      ],
    },
    {
      id: "on-sale",
      enabled: true,
      title: "On Sale",
      subtitle: "Great deals at amazing prices",
      badge: "SALE",
      columns: 4,
      cardStyle: "default",
      bgColor: "bg-white",
      products: [
        {
          id: 13,
          name: "Winter Care Gift Set",
          category: "Winter Care",
          price: 3599,
          originalPrice: 5999,
          discount: 40,
          rating: 4.6,
          reviews: 67,
          slug: "winter-gift-set",
          image: "https://placehold.co/300x300/1976D2/FFFFFF?text=Winter",
          badge: "SALE",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/1976D2/FFFFFF?text=Winter+1", "https://placehold.co/600x600/1565C0/FFFFFF?text=Winter+2"],
          description: `<h3>Complete Winter Care Gift Set</h3><p>Includes premium moisturizers, lip balms, and hand creams.</p>`,
        },
        {
          id: 14,
          name: "Vitamin C Serum - 30ml",
          category: "Beauty Care",
          price: 2399,
          originalPrice: 3599,
          discount: 33,
          rating: 4.4,
          reviews: 89,
          slug: "vitamin-c-serum",
          image: "https://placehold.co/300x300/F57C00/FFFFFF?text=Vitamin+C",
          badge: "SALE",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/F57C00/FFFFFF?text=Vitamin+C+1", "https://placehold.co/600x600/EF6C00/FFFFFF?text=Vitamin+C+2"],
          description: `<h3>Premium Vitamin C Serum</h3><p>Formulated with 20% pure Vitamin C for maximum results.</p>`,
        },
        {
          id: 15,
          name: "Hair Growth Oil - 100ml",
          category: "Hair Care",
          price: 2999,
          originalPrice: 4199,
          discount: 28,
          rating: 4.3,
          reviews: 56,
          slug: "hair-growth-oil",
          image: "https://placehold.co/300x300/7B1FA2/FFFFFF?text=Hair+Oil",
          badge: "SALE",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/7B1FA2/FFFFFF?text=Hair+Oil+1", "https://placehold.co/600x600/6A1B9A/FFFFFF?text=Hair+Oil+2"],
          description: `<h3>Natural Hair Growth Oil</h3><p>Formulated with rosemary, castor, and essential oils for healthy hair.</p>`,
        },
        {
          id: 16,
          name: "Baby Care Starter Kit",
          category: "Baby Care",
          price: 4199,
          originalPrice: 5999,
          discount: 30,
          rating: 4.8,
          reviews: 112,
          slug: "baby-care-kit",
          image: "https://placehold.co/300x300/EC407A/FFFFFF?text=Baby+Kit",
          badge: "SALE",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/EC407A/FFFFFF?text=Baby+Kit+1", "https://placehold.co/600x600/D81B60/FFFFFF?text=Baby+Kit+2"],
          description: `<h3>Complete Baby Care Starter Kit</h3><p>Includes gentle shampoo, moisturizer, diaper cream, and more.</p>`,
        },
        {
          id: 17,
          name: "Organic Matcha Green Tea",
          category: "Tea & Coffee",
          price: 1799,
          originalPrice: 2399,
          discount: 25,
          rating: 4.7,
          reviews: 43,
          slug: "matcha-green-tea",
          image: "https://placehold.co/300x300/4CAF50/FFFFFF?text=Matcha",
          badge: "SALE",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/4CAF50/FFFFFF?text=Matcha+1", "https://placehold.co/600x600/388E3C/FFFFFF?text=Matcha+2"],
          description: `<h3>Organic Matcha Green Tea</h3><p>Premium Japanese matcha green tea powder rich in antioxidants.</p>`,
        },
        {
          id: 18,
          name: "Aloe Vera Gel - Pure & Natural",
          category: "Skin Care",
          price: 899,
          originalPrice: 1299,
          discount: 30,
          rating: 4.6,
          reviews: 78,
          slug: "aloe-vera-gel",
          image: "https://placehold.co/300x300/4CAF50/FFFFFF?text=Aloe+Vera",
          badge: "SALE",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/4CAF50/FFFFFF?text=Aloe+Vera+1", "https://placehold.co/600x600/388E3C/FFFFFF?text=Aloe+Vera+2"],
          description: `<h3>Pure Aloe Vera Gel</h3><p>100% pure aloe vera gel from organic farms. Soothes and hydrates skin.</p>`,
        },
      ],
    },
    {
      id: "new-arrivals",
      enabled: true,
      title: "New Arrivals",
      subtitle: "Fresh products just added",
      badge: "NEW",
      columns: 4,
      cardStyle: "minimal",
      bgColor: "bg-white",
      products: [
        {
          id: 19,
          name: "Arabic Coffee - Premium Blend",
          category: "Tea & Coffee",
          price: 2639,
          originalPrice: null,
          rating: 4.5,
          reviews: 34,
          slug: "arabic-coffee",
          image: "https://placehold.co/300x300/3E2723/FFFFFF?text=Coffee",
          badge: "NEW",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/3E2723/FFFFFF?text=Coffee+1", "https://placehold.co/600x600/2C1A0E/FFFFFF?text=Coffee+2"],
          description: `<h3>Premium Arabic Coffee Blend</h3><p>Experience the rich, aromatic flavor of traditional Arabic coffee.</p>`,
        },
        {
          id: 20,
          name: "Rose Water Toner - 200ml",
          category: "Beauty Care",
          price: 2039,
          originalPrice: null,
          rating: 4.2,
          reviews: 45,
          slug: "rose-water-toner",
          image: "https://placehold.co/300x300/F48FB1/FFFFFF?text=Rose",
          badge: "NEW",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/F48FB1/FFFFFF?text=Rose+1", "https://placehold.co/600x600/F06292/FFFFFF?text=Rose+2"],
          description: `<h3>Natural Rose Water Toner</h3><p>Gently balances pH and provides natural hydration for your skin.</p>`,
        },
        {
          id: 21,
          name: "Oud Attar - 12ml",
          category: "Perfume & Attar",
          price: 4199,
          originalPrice: null,
          rating: 4.9,
          reviews: 78,
          slug: "oud-attar",
          image: "https://placehold.co/300x300/FFC107/FFFFFF?text=Oud",
          badge: "NEW",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/FFC107/FFFFFF?text=Oud+1", "https://placehold.co/600x600/FFB300/FFFFFF?text=Oud+2"],
          description: `<h3>Premium Oud Attar</h3><p>Experience the rich, woody fragrance of our premium Oud Attar.</p>`,
        },
        {
          id: 22,
          name: "Handmade Soap - Lavender",
          category: "Beauty Care",
          price: 1079,
          originalPrice: null,
          rating: 4.6,
          reviews: 23,
          slug: "lavender-soap",
          image: "https://placehold.co/300x300/E1BEE7/000000?text=Soap",
          badge: "NEW",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/E1BEE7/000000?text=Soap+1", "https://placehold.co/600x600/CE93D8/000000?text=Soap+2"],
          description: `<h3>Handmade Lavender Soap</h3><p>Gently cleanse and soothe your skin with our handmade lavender soap.</p>`,
        },
        {
          id: 23,
          name: "Omega-3 Fish Oil Capsules",
          category: "Supplements",
          price: 2999,
          originalPrice: null,
          rating: 4.9,
          reviews: 67,
          slug: "omega-3-fish-oil",
          image: "https://placehold.co/300x300/2196F3/FFFFFF?text=Omega-3",
          badge: "NEW",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/2196F3/FFFFFF?text=Omega-3+1", "https://placehold.co/600x600/1976D2/FFFFFF?text=Omega-3+2"],
          description: `<h3>Premium Omega-3 Fish Oil</h3><p>Supports heart health, brain function, and joint mobility.</p>`,
        },
        {
          id: 24,
          name: "Vitamin D3 - 2000 IU",
          category: "Supplements",
          price: 1799,
          originalPrice: 2399,
          discount: 25,
          rating: 4.8,
          reviews: 45,
          slug: "vitamin-d3",
          image: "https://placehold.co/300x300/FFD700/FFFFFF?text=Vitamin+D",
          badge: "NEW",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/FFD700/FFFFFF?text=Vitamin+D+1", "https://placehold.co/600x600/F9A825/FFFFFF?text=Vitamin+D+2"],
          description: `<h3>Vitamin D3 - 2000 IU</h3><p>Supports bone health, immune function, and overall well-being.</p>`,
        },
        {
          id: 25,
          name: "Organic Chia Seeds",
          category: "Foods",
          price: 899,
          originalPrice: null,
          rating: 4.7,
          reviews: 34,
          slug: "organic-chia-seeds",
          image: "https://placehold.co/300x300/8D6E63/FFFFFF?text=Chia+Seeds",
          badge: "NEW",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/8D6E63/FFFFFF?text=Chia+Seeds+1", "https://placehold.co/600x600/6D4C41/FFFFFF?text=Chia+Seeds+2"],
          description: `<h3>Organic Chia Seeds</h3><p>Packed with omega-3 fatty acids, fiber, and protein.</p>`,
        },
        {
          id: 26,
          name: "Himalayan Pink Salt - 1kg",
          category: "Spices",
          price: 699,
          originalPrice: 999,
          discount: 30,
          rating: 4.8,
          reviews: 56,
          slug: "himalayan-pink-salt",
          image: "https://placehold.co/300x300/F48FB1/FFFFFF?text=Pink+Salt",
          badge: "NEW",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/F48FB1/FFFFFF?text=Pink+Salt+1", "https://placehold.co/600x600/F06292/FFFFFF?text=Pink+Salt+2"],
          description: `<h3>Himalayan Pink Salt</h3><p>Pure Himalayan pink salt rich in minerals and trace elements.</p>`,
        },
      ],
    },
    {
      id: "health-wellness",
      enabled: true,
      title: "Health & Wellness",
      subtitle: "Natural supplements for a healthier life",
      badge: "POPULAR",
      columns: 4,
      cardStyle: "default",
      bgColor: "bg-emerald-50/30",
      products: [
        {
          id: 27,
          name: "Turmeric & Ginger Shot",
          category: "Supplements",
          price: 1199,
          originalPrice: 1599,
          discount: 25,
          rating: 4.7,
          reviews: 89,
          slug: "turmeric-ginger-shot",
          image: "https://placehold.co/300x300/F9A825/FFFFFF?text=Turmeric+Ginger",
          badge: "POPULAR",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/F9A825/FFFFFF?text=Turmeric+Ginger+1", "https://placehold.co/600x600/F57F17/FFFFFF?text=Turmeric+Ginger+2"],
          description: `<h3>Turmeric & Ginger Wellness Shot</h3><p>A potent blend for immune support and inflammation relief.</p>`,
        },
        {
          id: 28,
          name: "Collagen Peptides Powder",
          category: "Supplements",
          price: 3599,
          originalPrice: null,
          rating: 4.9,
          reviews: 112,
          slug: "collagen-peptides",
          image: "https://placehold.co/300x300/F5F5F5/000000?text=Collagen",
          badge: "TRENDING",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/F5F5F5/000000?text=Collagen+1", "https://placehold.co/600x600/E0E0E0/000000?text=Collagen+2"],
          description: `<h3>Hydrolyzed Collagen Peptides</h3><p>For skin, hair, joint, and bone health. Easily dissolves in liquids.</p>`,
        },
        {
          id: 29,
          name: "Ashwagandha Root Extract",
          category: "Supplements",
          price: 2399,
          originalPrice: 2999,
          discount: 20,
          rating: 4.6,
          reviews: 67,
          slug: "ashwagandha-extract",
          image: "https://placehold.co/300x300/4CAF50/FFFFFF?text=Ashwagandha",
          badge: "POPULAR",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/4CAF50/FFFFFF?text=Ashwagandha+1", "https://placehold.co/600x600/388E3C/FFFFFF?text=Ashwagandha+2"],
          description: `<h3>Ashwagandha Root Extract</h3><p>Reduces stress, improves sleep, and boosts energy naturally.</p>`,
        },
        {
          id: 30,
          name: "Probiotic 50 Billion CFU",
          category: "Supplements",
          price: 4199,
          originalPrice: 5199,
          discount: 20,
          rating: 4.8,
          reviews: 78,
          slug: "probiotic-50-billion",
          image: "https://placehold.co/300x300/7B1FA2/FFFFFF?text=Probiotic",
          badge: "TRENDING",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/7B1FA2/FFFFFF?text=Probiotic+1", "https://placehold.co/600x600/6A1B9A/FFFFFF?text=Probiotic+2"],
          description: `<h3>Probiotic 50 Billion CFU</h3><p>15 strains to support digestive health and immune function.</p>`,
        },
      ],
    },
    {
      id: "organic-foods",
      enabled: true,
      title: "Organic Foods",
      subtitle: "100% organic and chemical-free",
      badge: "ORGANIC",
      columns: 4,
      cardStyle: "featured",
      bgColor: "bg-green-50/30",
      products: [
        {
          id: 31,
          name: "Organic Quinoa - 500g",
          category: "Foods",
          price: 1499,
          originalPrice: 1899,
          discount: 21,
          rating: 4.7,
          reviews: 45,
          slug: "organic-quinoa",
          image: "https://placehold.co/300x300/F5F5F5/000000?text=Quinoa",
          badge: "ORGANIC",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/F5F5F5/000000?text=Quinoa+1", "https://placehold.co/600x600/E0E0E0/000000?text=Quinoa+2"],
          description: `<h3>Organic Quinoa</h3><p>100% organic quinoa, a complete protein source. Gluten-free and nutritious.</p>`,
        },
        {
          id: 32,
          name: "Organic Rolled Oats - 1kg",
          category: "Foods",
          price: 899,
          originalPrice: null,
          rating: 4.6,
          reviews: 34,
          slug: "organic-rolled-oats",
          image: "https://placehold.co/300x300/FFD700/FFFFFF?text=Oats",
          badge: "ORGANIC",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/FFD700/FFFFFF?text=Oats+1", "https://placehold.co/600x600/F9A825/FFFFFF?text=Oats+2"],
          description: `<h3>Organic Rolled Oats</h3><p>Rich in fiber, protein, and nutrients. Perfect for breakfast and baking.</p>`,
        },
        {
          id: 33,
          name: "Organic Coconut Sugar",
          category: "Foods",
          price: 699,
          originalPrice: 899,
          discount: 22,
          rating: 4.5,
          reviews: 23,
          slug: "organic-coconut-sugar",
          image: "https://placehold.co/300x300/8D6E63/FFFFFF?text=Coconut+Sugar",
          badge: "ORGANIC",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/8D6E63/FFFFFF?text=Coconut+Sugar+1", "https://placehold.co/600x600/6D4C41/FFFFFF?text=Coconut+Sugar+2"],
          description: `<h3>Organic Coconut Sugar</h3><p>Low glycemic index natural sweetener for baking and beverages.</p>`,
        },
        {
          id: 34,
          name: "Organic Black Pepper - 100g",
          category: "Spices",
          price: 499,
          originalPrice: null,
          rating: 4.8,
          reviews: 56,
          slug: "organic-black-pepper",
          image: "https://placehold.co/300x300/212121/FFFFFF?text=Black+Pepper",
          badge: "ORGANIC",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/212121/FFFFFF?text=Black+Pepper+1", "https://placehold.co/600x600/424242/FFFFFF?text=Black+Pepper+2"],
          description: `<h3>Organic Black Pepper</h3><p>Premium organic black peppercorns with a bold, aromatic flavor.</p>`,
        },
      ],
    },
    {
      id: "snacks-beverages",
      enabled: true,
      title: "Snacks & Beverages",
      subtitle: "Delicious treats and refreshing drinks",
      badge: "YUM",
      columns: 4,
      cardStyle: "default",
      bgColor: "bg-orange-50/30",
      products: [
        {
          id: 35,
          name: "Organic Dark Roast Coffee",
          category: "Tea & Coffee",
          price: 2999,
          originalPrice: 3599,
          discount: 16,
          rating: 4.9,
          reviews: 89,
          slug: "dark-roast-coffee",
          image: "https://placehold.co/300x300/3E2723/FFFFFF?text=Coffee+Beans",
          badge: "POPULAR",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/3E2723/FFFFFF?text=Coffee+Beans+1", "https://placehold.co/600x600/2C1A0E/FFFFFF?text=Coffee+Beans+2"],
          description: `<h3>Organic Dark Roast Coffee</h3><p>Bold, rich, and aromatic dark roast coffee beans. Perfect for espresso and drip coffee.</p>`,
        },
        {
          id: 36,
          name: "Herbal Tea Variety Pack",
          category: "Tea & Coffee",
          price: 1599,
          originalPrice: 1999,
          discount: 20,
          rating: 4.7,
          reviews: 67,
          slug: "herbal-tea-variety",
          image: "https://placehold.co/300x300/8D6E63/FFFFFF?text=Herbal+Tea",
          badge: "NEW",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/8D6E63/FFFFFF?text=Herbal+Tea+1", "https://placehold.co/600x600/6D4C41/FFFFFF?text=Herbal+Tea+2"],
          description: `<h3>Herbal Tea Variety Pack</h3><p>Assorted herbal teas including chamomile, peppermint, and ginger. Caffeine-free.</p>`,
        },
        {
          id: 37,
          name: "Premium Mixed Nuts",
          category: "Snacks",
          price: 2399,
          originalPrice: 2999,
          discount: 20,
          rating: 4.8,
          reviews: 123,
          slug: "premium-mixed-nuts",
          image: "https://placehold.co/300x300/D7CCC8/000000?text=Mixed+Nuts",
          badge: "BEST",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/D7CCC8/000000?text=Mixed+Nuts+1", "https://placehold.co/600x600/BCAAA4/000000?text=Mixed+Nuts+2"],
          description: `<h3>Premium Mixed Nuts</h3><p>A delicious blend of almonds, cashews, walnuts, and pistachios. Roasted and lightly salted.</p>`,
        },
        {
          id: 38,
          name: "Dried Fruit Medley",
          category: "Snacks",
          price: 1799,
          originalPrice: null,
          rating: 4.6,
          reviews: 78,
          slug: "dried-fruit-medley",
          image: "https://placehold.co/300x300/FFB300/FFFFFF?text=Dried+Fruit",
          badge: "POPULAR",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/FFB300/FFFFFF?text=Dried+Fruit+1", "https://placehold.co/600x600/F9A825/FFFFFF?text=Dried+Fruit+2"],
          description: `<h3>Dried Fruit Medley</h3><p>A delicious mix of dried apricots, raisins, figs, and dates. Naturally sweet and nutritious.</p>`,
        },
        {
          id: 39,
          name: "Coconut Water - 1L",
          category: "Beverages",
          price: 599,
          originalPrice: null,
          rating: 4.5,
          reviews: 45,
          slug: "coconut-water",
          image: "https://placehold.co/300x300/4CAF50/FFFFFF?text=Coconut+Water",
          badge: "NEW",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/4CAF50/FFFFFF?text=Coconut+Water+1", "https://placehold.co/600x600/388E3C/FFFFFF?text=Coconut+Water+2"],
          description: `<h3>Pure Coconut Water</h3><p>100% natural coconut water. Hydrating and rich in electrolytes. Perfect for hot days.</p>`,
        },
        {
          id: 40,
          name: "Protein Energy Bars - 12 Pack",
          category: "Snacks",
          price: 2399,
          originalPrice: 2999,
          discount: 20,
          rating: 4.4,
          reviews: 89,
          slug: "protein-energy-bars",
          image: "https://placehold.co/300x300/F57C00/FFFFFF?text=Protein+Bars",
          badge: "SALE",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/F57C00/FFFFFF?text=Protein+Bars+1", "https://placehold.co/600x600/EF6C00/FFFFFF?text=Protein+Bars+2"],
          description: `<h3>Protein Energy Bars</h3><p>High-protein energy bars with 20g protein per bar. Perfect for workouts and on-the-go nutrition.</p>`,
        },
      ],
    },
    {
      id: "beauty-personal-care",
      enabled: true,
      title: "Beauty & Personal Care",
      subtitle: "Premium products for your daily routine",
      badge: "GLOW",
      columns: 4,
      cardStyle: "default",
      bgColor: "bg-pink-50/30",
      products: [
        {
          id: 41,
          name: "Organic Argan Oil - 50ml",
          category: "Beauty Care",
          price: 2399,
          originalPrice: 2999,
          discount: 20,
          rating: 4.9,
          reviews: 156,
          slug: "organic-argan-oil",
          image: "https://placehold.co/300x300/F9A825/FFFFFF?text=Argan+Oil",
          badge: "BEST",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/F9A825/FFFFFF?text=Argan+Oil+1", "https://placehold.co/600x600/F57F17/FFFFFF?text=Argan+Oil+2"],
          description: `<h3>Organic Argan Oil</h3><p>100% pure Moroccan argan oil. Nourishes hair, skin, and nails. Rich in Vitamin E and fatty acids.</p>`,
        },
        {
          id: 42,
          name: "Jojoba Oil - 100ml",
          category: "Beauty Care",
          price: 1799,
          originalPrice: 2399,
          discount: 25,
          rating: 4.7,
          reviews: 89,
          slug: "jojoba-oil",
          image: "https://placehold.co/300x300/FFD700/FFFFFF?text=Jojoba+Oil",
          badge: "POPULAR",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/FFD700/FFFFFF?text=Jojoba+Oil+1", "https://placehold.co/600x600/F9A825/FFFFFF?text=Jojoba+Oil+2"],
          description: `<h3>Pure Jojoba Oil</h3><p>Cold-pressed jojoba oil that mimics skin's natural sebum. Great for moisturizing and makeup removal.</p>`,
        },
        {
          id: 43,
          name: "Natural Lip Balm Set",
          category: "Beauty Care",
          price: 899,
          originalPrice: null,
          rating: 4.8,
          reviews: 67,
          slug: "natural-lip-balm-set",
          image: "https://placehold.co/300x300/EC407A/FFFFFF?text=Lip+Balm",
          badge: "NEW",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/EC407A/FFFFFF?text=Lip+Balm+1", "https://placehold.co/600x600/D81B60/FFFFFF?text=Lip+Balm+2"],
          description: `<h3>Natural Lip Balm Set</h3><p>Set of 4 natural lip balms in different flavors. Moisturizes and protects lips.</p>`,
        },
        {
          id: 44,
          name: "Tea Tree Oil - 30ml",
          category: "Balm/Ointment",
          price: 1199,
          originalPrice: 1599,
          discount: 25,
          rating: 4.9,
          reviews: 123,
          slug: "tea-tree-oil",
          image: "https://placehold.co/300x300/4CAF50/FFFFFF?text=Tea+Tree",
          badge: "BEST",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/4CAF50/FFFFFF?text=Tea+Tree+1", "https://placehold.co/600x600/388E3C/FFFFFF?text=Tea+Tree+2"],
          description: `<h3>Pure Tea Tree Oil</h3><p>Premium Australian tea tree oil. Known for its antiseptic and antimicrobial properties.</p>`,
        },
        {
          id: 45,
          name: "Lavender Essential Oil - 15ml",
          category: "Balm/Ointment",
          price: 899,
          originalPrice: 1199,
          discount: 25,
          rating: 4.7,
          reviews: 89,
          slug: "lavender-essential-oil",
          image: "https://placehold.co/300x300/CE93D8/FFFFFF?text=Lavender+Oil",
          badge: "POPULAR",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/CE93D8/FFFFFF?text=Lavender+Oil+1", "https://placehold.co/600x600/BA68C8/FFFFFF?text=Lavender+Oil+2"],
          description: `<h3>Lavender Essential Oil</h3><p>Pure lavender essential oil for relaxation, sleep, and aromatherapy. Calming and soothing.</p>`,
        },
        {
          id: 46,
          name: "Natural Deodorant Stick",
          category: "Beauty Care",
          price: 1079,
          originalPrice: null,
          rating: 4.5,
          reviews: 56,
          slug: "natural-deodorant",
          image: "https://placehold.co/300x300/8D6E63/FFFFFF?text=Deodorant",
          badge: "NEW",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/8D6E63/FFFFFF?text=Deodorant+1", "https://placehold.co/600x600/6D4C41/FFFFFF?text=Deodorant+2"],
          description: `<h3>Natural Deodorant Stick</h3><p>Aluminum-free natural deodorant with essential oils. Keeps you fresh all day.</p>`,
        },
      ],
    },
    {
      id: "oral-hygiene",
      enabled: true,
      title: "Oral Hygiene",
      subtitle: "Keep your smile bright and healthy",
      badge: "CARE",
      columns: 4,
      cardStyle: "minimal",
      bgColor: "bg-blue-50/30",
      products: [
        {
          id: 47,
          name: "Activated Charcoal Toothpaste",
          category: "Oral Care",
          price: 899,
          originalPrice: 1299,
          discount: 30,
          rating: 4.6,
          reviews: 78,
          slug: "charcoal-toothpaste",
          image: "https://placehold.co/300x300/212121/FFFFFF?text=Charcoal",
          badge: "POPULAR",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/212121/FFFFFF?text=Charcoal+1", "https://placehold.co/600x600/424242/FFFFFF?text=Charcoal+2"],
          description: `<h3>Activated Charcoal Toothpaste</h3><p>Natural whitening toothpaste with activated charcoal. Removes stains and freshens breath.</p>`,
        },
        {
          id: 48,
          name: "Bamboo Toothbrush Set",
          category: "Oral Care",
          price: 699,
          originalPrice: null,
          rating: 4.9,
          reviews: 134,
          slug: "bamboo-toothbrush-set",
          image: "https://placehold.co/300x300/8BC34A/FFFFFF?text=Bamboo",
          badge: "BEST",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/8BC34A/FFFFFF?text=Bamboo+1", "https://placehold.co/600x600/689F38/FFFFFF?text=Bamboo+2"],
          description: `<h3>Bamboo Toothbrush Set</h3><p>Eco-friendly bamboo toothbrushes with soft bristles. Set of 4 with charcoal-infused bristles.</p>`,
        },
        {
          id: 49,
          name: "Natural Mouthwash - 500ml",
          category: "Oral Care",
          price: 599,
          originalPrice: 799,
          discount: 25,
          rating: 4.4,
          reviews: 45,
          slug: "natural-mouthwash",
          image: "https://placehold.co/300x300/4CAF50/FFFFFF?text=Mouthwash",
          badge: "NEW",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/4CAF50/FFFFFF?text=Mouthwash+1", "https://placehold.co/600x600/388E3C/FFFFFF?text=Mouthwash+2"],
          description: `<h3>Natural Mouthwash</h3><p>Alcohol-free natural mouthwash with peppermint oil. Freshens breath and kills bacteria.</p>`,
        },
        {
          id: 50,
          name: "Dental Floss - Eco-Friendly",
          category: "Oral Care",
          price: 399,
          originalPrice: null,
          rating: 4.7,
          reviews: 34,
          slug: "eco-floss",
          image: "https://placehold.co/300x300/F5F5F5/000000?text=Floss",
          badge: "NEW",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/F5F5F5/000000?text=Floss+1", "https://placehold.co/600x600/E0E0E0/000000?text=Floss+2"],
          description: `<h3>Eco-Friendly Dental Floss</h3><p>Biodegradable dental floss with natural wax. Effectively removes plaque and food particles.</p>`,
        },
      ],
    },
    {
      id: "fragrance",
      enabled: true,
      title: "Fragrance Collection",
      subtitle: "Find your signature scent",
      badge: "SCENT",
      columns: 4,
      cardStyle: "default",
      bgColor: "bg-purple-50/30",
      products: [
        {
          id: 51,
          name: "Rose Attar - 10ml",
          category: "Fragrance",
          price: 2999,
          originalPrice: 3599,
          discount: 16,
          rating: 4.8,
          reviews: 67,
          slug: "rose-attar",
          image: "https://placehold.co/300x300/EC407A/FFFFFF?text=Rose+Attar",
          badge: "BEST",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/EC407A/FFFFFF?text=Rose+Attar+1", "https://placehold.co/600x600/D81B60/FFFFFF?text=Rose+Attar+2"],
          description: `<h3>Pure Rose Attar</h3><p>Traditional rose attar with a rich, floral fragrance. Long-lasting and alcohol-free.</p>`,
        },
        {
          id: 52,
          name: "Musk Attar - 10ml",
          category: "Fragrance",
          price: 3599,
          originalPrice: null,
          rating: 4.9,
          reviews: 89,
          slug: "musk-attar",
          image: "https://placehold.co/300x300/4E342E/FFFFFF?text=Musk+Attar",
          badge: "POPULAR",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/4E342E/FFFFFF?text=Musk+Attar+1", "https://placehold.co/600x600/3E2723/FFFFFF?text=Musk+Attar+2"],
          description: `<h3>Premium Musk Attar</h3><p>Exquisite musk attar with a warm, sensual fragrance. Perfect for special occasions.</p>`,
        },
        {
          id: 53,
          name: "Jasmine Attar - 10ml",
          category: "Fragrance",
          price: 2799,
          originalPrice: 3399,
          discount: 17,
          rating: 4.7,
          reviews: 56,
          slug: "jasmine-attar",
          image: "https://placehold.co/300x300/F48FB1/FFFFFF?text=Jasmine",
          badge: "NEW",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/F48FB1/FFFFFF?text=Jasmine+1", "https://placehold.co/600x600/F06292/FFFFFF?text=Jasmine+2"],
          description: `<h3>Pure Jasmine Attar</h3><p>Sweet and exotic jasmine attar with a captivating floral fragrance.</p>`,
        },
        {
          id: 54,
          name: "Saffron Attar - 10ml",
          category: "Fragrance",
          price: 4799,
          originalPrice: null,
          rating: 4.9,
          reviews: 78,
          slug: "saffron-attar",
          image: "https://placehold.co/300x300/FFC107/FFFFFF?text=Saffron",
          badge: "LUXURY",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/FFC107/FFFFFF?text=Saffron+1", "https://placehold.co/600x600/FFB300/FFFFFF?text=Saffron+2"],
          description: `<h3>Premium Saffron Attar</h3><p>Luxurious saffron attar with a unique, exotic fragrance. Rare and highly prized.</p>`,
        },
      ],
    },
    {
      id: "health-devices",
      enabled: true,
      title: "Health & Wellness Devices",
      subtitle: "Smart gadgets for a healthier life",
      badge: "TECH",
      columns: 4,
      cardStyle: "default",
      bgColor: "bg-slate-50/50",
      products: [
        {
          id: 55,
          name: "Digital Blood Pressure Monitor",
          category: "Gear & Gadgets",
          price: 5999,
          originalPrice: 7999,
          discount: 25,
          rating: 4.8,
          reviews: 134,
          slug: "blood-pressure-monitor",
          image: "https://placehold.co/300x300/1976D2/FFFFFF?text=BP+Monitor",
          badge: "POPULAR",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/1976D2/FFFFFF?text=BP+Monitor+1", "https://placehold.co/600x600/1565C0/FFFFFF?text=BP+Monitor+2"],
          description: `<h3>Digital Blood Pressure Monitor</h3><p>Accurate and easy-to-use digital blood pressure monitor. Large display and memory function.</p>`,
        },
        {
          id: 56,
          name: "Smart Fitness Tracker",
          category: "Gear & Gadgets",
          price: 8999,
          originalPrice: 11999,
          discount: 25,
          rating: 4.7,
          reviews: 89,
          slug: "fitness-tracker",
          image: "https://placehold.co/300x300/2196F3/FFFFFF?text=Fitness+Tracker",
          badge: "NEW",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/2196F3/FFFFFF?text=Fitness+Tracker+1", "https://placehold.co/600x600/1976D2/FFFFFF?text=Fitness+Tracker+2"],
          description: `<h3>Smart Fitness Tracker</h3><p>Track steps, heart rate, sleep, and more. Water-resistant with long battery life.</p>`,
        },
        {
          id: 57,
          name: "Digital Thermometer - Contactless",
          category: "Gear & Gadgets",
          price: 2999,
          originalPrice: null,
          rating: 4.6,
          reviews: 78,
          slug: "contactless-thermometer",
          image: "https://placehold.co/300x300/4CAF50/FFFFFF?text=Thermometer",
          badge: "POPULAR",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/4CAF50/FFFFFF?text=Thermometer+1", "https://placehold.co/600x600/388E3C/FFFFFF?text=Thermometer+2"],
          description: `<h3>Contactless Digital Thermometer</h3><p>Non-contact infrared thermometer for accurate temperature readings. Safe and hygienic.</p>`,
        },
        {
          id: 58,
          name: "Weight Scale - Smart",
          category: "Gear & Gadgets",
          price: 3999,
          originalPrice: 4999,
          discount: 20,
          rating: 4.5,
          reviews: 56,
          slug: "smart-scale",
          image: "https://placehold.co/300x300/F5F5F5/000000?text=Scale",
          badge: "NEW",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/F5F5F5/000000?text=Scale+1", "https://placehold.co/600x600/E0E0E0/000000?text=Scale+2"],
          description: `<h3>Smart Weight Scale</h3><p>Connected smart scale that tracks body weight, BMI, and body fat percentage.</p>`,
        },
      ],
    },
    {
      id: "premium-collection",
      enabled: true,
      title: "Premium Collection",
      subtitle: "Luxury products for discerning customers",
      badge: "LUXURY",
      columns: 4,
      cardStyle: "featured",
      bgColor: "bg-amber-50/20",
      products: [
        {
          id: 59,
          name: "Premium Manuka Honey - MGO 100+",
          category: "Honey",
          price: 8999,
          originalPrice: 11999,
          discount: 25,
          rating: 4.9,
          reviews: 234,
          slug: "manuka-honey",
          image: "https://placehold.co/300x300/FFB300/FFFFFF?text=Manuka",
          badge: "PREMIUM",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/FFB300/FFFFFF?text=Manuka+1", "https://placehold.co/600x600/F9A825/FFFFFF?text=Manuka+2"],
          description: `<h3>Premium Manuka Honey</h3><p>New Zealand Manuka honey with MGO 100+. Known for its unique antibacterial properties.</p>`,
        },
        {
          id: 60,
          name: "Saffron - Premium Grade",
          category: "Spices",
          price: 11999,
          originalPrice: 14999,
          discount: 20,
          rating: 4.9,
          reviews: 167,
          slug: "premium-saffron",
          image: "https://placehold.co/300x300/FFC107/FFFFFF?text=Saffron",
          badge: "PREMIUM",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/FFC107/FFFFFF?text=Saffron+1", "https://placehold.co/600x600/FFB300/FFFFFF?text=Saffron+2"],
          description: `<h3>Premium Grade Saffron</h3><p>High-quality Persian saffron threads with intense color and aroma. The world's most expensive spice.</p>`,
        },
        {
          id: 61,
          name: "Ginseng Root Extract",
          category: "Supplements",
          price: 5399,
          originalPrice: null,
          rating: 4.8,
          reviews: 89,
          slug: "ginseng-extract",
          image: "https://placehold.co/300x300/8D6E63/FFFFFF?text=Ginseng",
          badge: "PREMIUM",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/8D6E63/FFFFFF?text=Ginseng+1", "https://placehold.co/600x600/6D4C41/FFFFFF?text=Ginseng+2"],
          description: `<h3>Korean Ginseng Extract</h3><p>Premium Korean red ginseng extract. Known for its adaptogenic properties and energy-boosting benefits.</p>`,
        },
        {
          id: 62,
          name: "Premium Dates Gift Box",
          category: "Dates",
          price: 3599,
          originalPrice: 4599,
          discount: 22,
          rating: 4.8,
          reviews: 145,
          slug: "premium-dates-giftbox",
          image: "https://placehold.co/300x300/8D6E63/FFFFFF?text=Gift+Box",
          badge: "PREMIUM",
          brand: "SazzBazar",
          inStock: true,
          images: ["https://placehold.co/600x600/8D6E63/FFFFFF?text=Gift+Box+1", "https://placehold.co/600x600/6D4C41/FFFFFF?text=Gift+Box+2"],
          description: `<h3>Premium Dates Gift Box</h3><p>Elegantly packaged premium dates in a beautiful gift box. Perfect for gifting.</p>`,
        },
      ],
    },
  ],

  // Ad sections
  adSections: [
    {
      id: "ad-1",
      enabled: true,
      position: "after-featured",
      size: "compact",
      bgGradient: "from-indigo-600 to-purple-600",
      title: "Advertise With Us",
      subtitle: "Reach 5,000+ daily visitors",
      ctaText: "Place Your Ad",
      visitorCount: "5,000+ Daily Visitors",
    },
    {
      id: "ad-2",
      enabled: true,
      position: "after-on-sale",
      size: "default",
      bgGradient: "from-cyan-600 to-blue-600",
      title: "Promote Your Brand Here",
      subtitle: "Reach thousands of potential customers",
      ctaText: "Advertise Now",
      visitorCount: "10,000+ Monthly Visitors",
    },
    {
      id: "ad-3",
      enabled: true,
      position: "after-new-arrivals",
      size: "large",
      bgGradient: "from-amber-600 to-orange-600",
      title: "📢 Advertise With SazzBazar",
      subtitle: "Get featured on our homepage and reach thousands of customers daily",
      ctaText: "Get Started",
      visitorCount: "10,000+ Happy Customers",
    },
    {
      id: "ad-4",
      enabled: true,
      position: "after-health-wellness",
      size: "default",
      bgGradient: "from-emerald-600 to-teal-600",
      title: "💚 Health & Wellness Partner",
      subtitle: "Promote your brand to health-conscious customers",
      ctaText: "Advertise Now",
      visitorCount: "5,000+ Health Enthusiasts",
    },
    {
      id: "ad-5",
      enabled: true,
      position: "after-beauty-personal-care",
      size: "compact",
      bgGradient: "from-pink-600 to-rose-600",
      title: "✨ Beauty Brand Spotlight",
      subtitle: "Reach beauty enthusiasts",
      ctaText: "Advertise Here",
      visitorCount: "8,000+ Beauty Lovers",
    },
  ],

  // Contact info for Buy Now
  contactInfo: {
    whatsapp: "+8801818186097",
    phone: "+8801818186097",
  },

  // Delivery info
  deliveryInfo: {
    freeShipping: true,
    estimatedDays: "2-4",
    returnPolicy: "30 days",
    warranty: "1 year",
    inStock: true,
  },
};